resources:
  - name: Maven-Sample-App
    type: git
    source:
      uri: https://github.com/imnitin28/concourse-cicd.git
      branch: main

jobs:
  - name: test
    public: true

    plan:
      - get: Maven-Sample-App
        trigger: true
      - task: mvn-test
        file: "maven-test.yml"
