resources:
  - name: maven-app
    type: git
    source:
      uri: https://github.com/imnitin28/concourse-cicd.git
      branch: main

jobs:
  - name: test
    public: true

    plan:
      - get: Maven-Sample-App
        trigger: true
      - task: mvn-test
        file: "./Maven-Sample-App/ci-scripts/tasks/maven-test.yml"
